# Generated by Django 5.2.1 on 2025-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(blank=True, default='Anónimo', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(blank=True, default='', verbose_name='Breve resumen'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(blank=True, default='', verbose_name='Artículo completo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
