# Generated by Django 5.2.1 on 2025-06-02 19:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articulo_fecha_publicacion_articulo_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='created_at',
            field=models.DateTimeField(default=blog.models.default_created_at),
        ),
    ]
